// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ems_persistencia;

#nullable disable

namespace ems_persistencia.Migrations
{
    [DbContext(typeof(EmsLiteDbContext))]
    [Migration("20240611200158_EliminaTablaPeople2")]
    partial class EliminaTablaPeople2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1");

            modelBuilder.Entity("ems_persistencia.ConfiguracionArranque", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("capacidad_bateria_segura")
                        .HasColumnType("REAL");

                    b.Property<double>("capacidad_baterias")
                        .HasColumnType("REAL");

                    b.Property<double>("demanda_contratada")
                        .HasColumnType("REAL");

                    b.Property<double>("limite_demanda")
                        .HasColumnType("REAL");

                    b.Property<double>("porcentaje_carga_segura")
                        .HasColumnType("REAL");

                    b.Property<double>("porcentaje_respaldo_energía")
                        .HasColumnType("REAL");

                    b.Property<double>("potencia_baterias")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("ConfiguracionArranque");
                });
#pragma warning restore 612, 618
        }
    }
}
